name: LSIF
on:
  - push
jobs:
  lsif-ts:
    runs-on: ubuntu-latest
    container: sourcegraph/lsif-node
    steps:
      - uses: actions/checkout@v1
      - name: Install build dependencies
        run: apk --no-cache add python g++ make git
      - name: Install dependencies
        run: yarn install
      - name: Generate LSIF data
        run: lsif-tsc -p .
      - name: Upload LSIF data
        run: src lsif upload -github-token=${{ secrets.GITHUB_TOKEN }}
